### PR TITLE
New features

### PR DESCRIPTION
**Pull request by lk-geimfari**
So, here some new features and fixed both issues: #300, #263.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@sobolevn Any comments?

**Comment by sobolevn** [comment]
Sorry, don't have any time to check this out. Can this be done next week?

**Comment by lk-geimfari** [comment]
@sobolevn Sure!

**Comment by lk-geimfari** [comment]
I checked everything myself. As I can judge, everything is okay. I'll merge this PR, because here are only refactoring and few new methods.

**Pull request merged**
