### PR TITLE
Do the chores: update tools, fix CI scripts, improve Makefile

### PR DESCRIPTION
**Pull request by sobolevn**
What I've done:
1. New script to check code style
2. New makefile features
3. Updated mypy and code to match new rules
4. Updated deps
5. New CI workflow to use actual scripts
6. Remove several unused deps

### CODE REVIEW

**Comment by sobolevn** [comment]
I think we can release a new version after merging this!

**Review by lk-geimfari — APPROVED** [review]

**Comment by lk-geimfari** [comment]
Looks great to me! Thank you!

**Comment by lk-geimfari** [comment]
@sobolevn Can I merge this PR? Any other additions?

**Comment by lk-geimfari** [comment]
@sobolevn 🏓

**Comment by sobolevn** [comment]
It now has merge conflicts :(

**Pull request merged**
