### PR TITLE
Some fixes for issue #325

### PR DESCRIPTION
**Pull request by duckyou**
https://github.com/lk-geimfari/mimesis/issues/325#issuecomment-352356998

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@duckyou I'll do a full review a little later and if it's okay - I'll merge it.

P.S Don't forget to add yourself to `CONTRIBUTORS.md`.

**Comment by lk-geimfari** [comment]
@duckyou So, there one big problem. I think that testing all methods with `seed` is too painful and hard to maintain. We cant write two different tests for one method every time when we create new methods. I suggest removing this tests. We can test `seed` only using `BaseProvider`, i.e in file `test_base.py` if seed works for it, it will mean that `seed` works for all subclasses of `BaseProvider`:

```python
@pytest.fixture
def seeded_base():
    return BaseProvider(seed=42)

def test_base_with_seed(seeded_base):
    result = seeded_base.random.randint(1, 10)
    assert result == 2
```

**What should be done:** Remove all the tests which were added and replace them with the code above.

**Comment by lk-geimfari** [comment]
@duckyou You are probably already tired of making corrections, but we must support the simplicity of the project and its tests. If you do not want to do this, then I understand you and I will do it myself. Thanks!

**Comment by duckyou** [comment]
@lk-geimfari 

> @duckyou So, there one big problem. I think that testing all methods with seed is too painful and hard to maintain. We cant write two different tests for one method every time when we create new methods. I suggest removing this tests. We can test seed only using BaseProvider.

I partly agree. Two different tests for one method is awful design... my bad =(
But write tests only for BaseProvider also bad decision. Heres eg:
https://github.com/lk-geimfari/mimesis/pull/327/commits/53e19b8db4eda89d7c595dbc568b9566243ec2f1#diff-fb2e53700ab7e63642efe387f905686a
```python
    def words(self, quantity: int = 5) -> list:
        # Here is issue... some times normal words returnes in random order
        words = self._data['words'].get('normal')
        # Heres fix... when seed seted, its sorted words
        if self.seed: 
            words = sorted(words)
        words_list = [self.random.choice(words) for _ in range(quantity)]
        return words_list
```

IMHO Seed tests should be for each method. I recommend merge seed tests with its basic.

**Comment by lk-geimfari** [comment]
@duckyou So, the situation with the previous PR was repeated here (not without my help). I'll create a new branch and applied your changes in this branch, but partially to better understanding what is happens.

**Comment by lk-geimfari** [comment]
@duckyou I'll do it tomorrow, but for now, we'll leave it as it at that. Do not change anything, please.

**Comment by lk-geimfari** [comment]
This PR was merged partially, as I said in our discussion.

**Pull request closed without merging**
