### PR TITLE
Fix types for Seed.

### PR DESCRIPTION
**Pull request by ngnpope**
Makes the following changes:

- Added `float` to the `Union` for `Seed`.
- Added `None` to the `Union` for `Seed`.
- Replaced `Optional[Seed]` with `Seed` everywhere.

See the following links for details:

- https://bugs.python.org/issue32554
- https://github.com/python/cpython/pull/15382
- https://docs.python.org/3.9/library/random.html#random.seed

Currently `typeshed` is still using `Any`.

## Checklist

- [x] I have read [contributing guidelines](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst)
- [x] I'm sure that I did not unrelated changes in this pull request
- [n/a] I have created at least one test case for the changes I have made

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@ngnpopePlease, fix the issues (see details for github actions)

**Comment by ngnpope** [comment]
Sure. (I'd noticed but just don't have time to get back to it this weekend. Will resolve in a few days.)

**Comment by ngnpope** [comment]
Hopefully I've fixed all the issues. Sorry for the laziness and the noise!

**Comment by lk-geimfari** [comment]
@ngnpope You did a great job! Thank you very much!

**Pull request merged**
