### PR TITLE
[WIP] Implemented #387

### PR DESCRIPTION
**Pull request by lk-geimfari**
How it works:

When we define locale, methods just returns approximate coordinates for current locale (country):
```python
>>> ad = Address('de') # It will return coordinates for Germany
>>> ad.coordinates()
{'latitude': 47.523907, 'longitude': 12.963119}
```
screenshot from 2018-01-23 14-36-26

But I don't know how to be with passing an optional range of coordinates. For example, we have created an instance for de, but want to generate random coordinates.

Should we use do it like this:
```python
>>> ad.coordinates(country_code='any')
```

Or, maybe like this:

```python
>>> ad.coordinates(country_code=...)
```

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@sobolevn @duckyou Your opinion, please.

**Comment by duckyou** [comment]
@lk-geimfari Coordinates is **locale pattern** independent data, but sometimes it should be depend on **country locale**... hmm... Maybe migrate this method to international provider?

**Comment by lk-geimfari** [comment]
@duckyou I have added ones to JSON files for easy creating data for a defined locale. Maybe you're right. Can you please suggest your solution, when you'll have free time. All the needed data you can grab forked this branch.a

**Comment by lk-geimfari** [comment]
My solution looks not good.

**Pull request closed without merging**
