### PR TITLE
Move pytest plugin

### LINKED ISSUE #1489: Codecov reporting wrong coverage information.
I have no idea why, but commit 79f6257 (`Add pytest entry in pyproject.toml`) decreased coverage by [42.21%](https://app.codecov.io/gh/lk-geimfari/mimesis/commit/79f625782f7cf0ff1943635abe9cfdc9961ae3f3/indirect-changes). Clearly, Codecov is reporting incorrect coverage information and the question is "Why"?

### PR DESCRIPTION
**Pull request by mheguy-flo**
This resolves the issue with code coverage and all tests pass, but I don't know if it does/will have a negative impact on the plugin itself for end users.

Closes #1489

### CODE REVIEW

**Comment by lk-geimfari** [comment]
Seems like id does not fix that issue: https://app.codecov.io/gh/lk-geimfari/mimesis/pull/1522

**Comment by mheguy-flo** [comment]
Sorry about that. I must have gotten mixed up between stashes at one point.

**Review by sobolevn — COMMENTED** [review]
I am pretty sure that the current `pyproject.toml` won't include this folder into the ending build.

Plus, `pytest_plugin` name is too generic. Maybe `mimesis_pytest_plugin`?

**Comment by mheguy-flo** [comment]
With the latest commits, this is what it looks like after a pip install:
image

I don't know if this is how you guys want it / how it should be.

**Pull request closed without merging**
