### PR TITLE
added "et" locale (Estonian)

### PR DESCRIPTION
**Pull request by Valerievich**
Added the new locale 'et' and needed dependencies for tests.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@Valerievich Great work! It's still in work or it's done? Can i merge this Pull Request?

**Comment by lk-geimfari** [comment]
@Valerievich Please, if it does not complicate you, add `et` to the list of supported languages in [README.md](https://github.com/lk-geimfari/mimesis#locales).

Example:

| №  | Flag  | Code       | Name                 | Native name |
|--- |---   |---       |---                 |---         |
| 3  | 🇪🇪   |  `et`      | Estonian               | Eesti     |

**Comment by Valerievich** [comment]
I've updated `README.md` ;) and yes u can merge this PR.

**Comment by lk-geimfari** [comment]
@Valerievich Thank you!

**Pull request merged**
