### PR TITLE
Update CONTRIBUTORS.rst

### PR DESCRIPTION
**Pull request by Vlangf**

### CODE REVIEW

**Comment by lk-geimfari** [comment]
I don't see your contribution to this project. Are you sure that you've created this PR for the correct repository?

image

**Comment by Vlangf** [comment]
I added myself in list of contributors. I made generate kpp(issue #318), but i can't send PR - error 403.

**Comment by lk-geimfari** [comment]
@Vlangf Can you please give me a link to the code? Can you retry to create PR, please?

**Comment by Vlangf** [comment]
I retried to create PR and now successfully :)

**Pull request closed without merging**
