### PR TITLE
TODO: Resolve importing errors and use importing format as above.

### PR DESCRIPTION
**Pull request by Valerievich**
In this PL: 1) all import errors were resolved 2) import format in generic.py was changed.
All tests passed.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@Valerievich Are you tried this format?

```python
from mimesis.providers import Games
```
Erorrs raised only when we use following format. General questions is "Why?" and "What we need to do to fix this." I think you agree that is will much better use similar format for importing all providers from `providers`.

How it should looks like:

```python
# All providers from `providers`
from mimesis.providers import (Address, BaseProvider, Business, ClothingSizes, Code, Datetime, 
                               Development, File, Food, Games, Hardware, Personal, ...)
```

**Comment by Valerievich** [comment]
Yes, I tried format 
```python
from mimesis.providers import Games
```
It leads to import errors in generic.py

**Comment by Valerievich** [comment]
Ok, then. I will try to use proposed format one more time and answer the question "What we need to do to fix this."

**Comment by lk-geimfari** [comment]
@Valerievich Thank you!

**Pull request closed without merging**
