### PR TITLE
Drop `setup.py` script

### PR DESCRIPTION
**Pull request by hoefling**
### Changes:

* `setup.py` is removed
* `python setup.py minify` becomes `poetry run task minify` (uses `taskipy`), minifier impl reworked, now resides in `minifier.py`
* `python check --restructuredtext --strict` becomes `twine check --strict`

## Checklist

- [x] I have read [contributing guidelines](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst)
- [x] I'm sure that I did not unrelated changes in this pull request
- [x] I have created at least one test case for the changes I have made

- ~~[ ] I have updated the documentation for the changes I have made~~ should not be necessary for CI changes

- [ ] I have added my changes to the [CHANGELOG.rst](https://github.com/lk-geimfari/mimesis/blob/master/CHANGELOG.rst)
Is a changelog update necessary for this?

### CODE REVIEW

**Review by lk-geimfari — APPROVED** [review]

**Comment by lk-geimfari** [comment]
@hoefling Great job! Thank you! Can I merge it?

**Comment by lk-geimfari** [comment]
@hoefling Also, I see that you're from Germany, so if you are interested then It would be really helpful to check the correctness of data for locale `de`.

**Comment by lk-geimfari** [comment]
Whatever it is, thanks for your contribution!

**Comment by hoefling** [comment]
@lk-geimfari I guess so, except for the coverage drop - I can try adding a test that reaches some uncovered lines to amend that. As for the spell checks - can do, although we are haven't noticed anything worth mentioning so far, so I'm pretty sure it's solid. Could extend the list of streets a bit, though.

**Comment by lk-geimfari** [comment]
Great! I'll wait for your new PR. I'm merging this one.

**Pull request merged**
