### PR TITLE
Add pytest-randomly seedsetting functionto Makefile

### LINKED ISSUE #468: Add pytest-randomly
We need to run tests in random order to be sure, that they do not depend on each other.

https://github.com/pytest-dev/pytest-randomly

### PR DESCRIPTION
**Pull request by tabassco**
# I have made things!

Hey there. This is my first pull request for an open source project. :)

## Checklist

- [x] I have read [contributing guidelines](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst)
- [x] I'm sure that I did not unrelated changes in this pull request
- [ ] I have created at least one test case for the changes I have made

- [x] I have added myself to the [CONTRIBUTORS.rst](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTORS.rst)

## Related issues

- Closes #468 

## Ideas

I've already described my ideas in my first draft in the issues thread. 

But what it boils down to:

Give the option to specify the --randomly-seed option from the Makefile to make easier use of this feature. 

I have updated the contributing guide to introduce the feature.

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@tabassco Hi! Thank you for your interest! Can you please add it to the travis.yml file to make sure that this solution really works? Thank you!

**Comment by tabassco** [comment]
@lk-geimfari Thanks for your reply. I'm not quite sure where I'd merge it as it is only a change to the Makefile that would be run locally and not the travis.yml file. As pytest-randomly is already in the dependencies in poetry it will be used to shuffle the tests everytime without any changes.

If you could point me in the right direction I'll do so right away.

**Comment by lk-geimfari** [comment]
@tabassco Are you saying that it (random shuffling) works on Travis already? Sorry, I'm not quite sure that I understood you correctly.

**Comment by tabassco** [comment]
@lk-geimfari Yes. Exactly.

Taking a look at the job protocol from my run: 
```
============================= test session starts ==============================
platform linux -- Python 3.7.1, pytest-5.4.2, py-1.8.1, pluggy-0.13.1
Using --randomly-seed=1589317930
rootdir: /home/travis/build/lk-geimfari/mimesis, inifile: setup.cfg
plugins: isort-1.0.0, cov-2.8.1, flake8-1.0.5, randomly-3.3.1, mock-3.1.0
collected 4477 items    
```
You can get the randomly-seed from there and plug it into your local setup using the Makefile changes I made. Then you will get the same ordering for the tests to do debugging.

**Comment by lk-geimfari** [comment]
@tabassco Thank you!

**Pull request merged**
