### PR TITLE
Add `pytest-randomly` integration by introducing `random.global_state`

### PR DESCRIPTION
**Pull request by sobolevn**
Main points:
1. We now have global random state that can be set via any plugin / tool
2. You can still override the global state by explicit `seed=` argument to any provider / field
3. Docs now mention `pytest-randomly` support
4. I've added a bunch of tests for this new feature
5. But, I am not fully agree with `unique=True` and `seed` parameters behaviour. But, I left this as-is for another PR after a proper discussion

To help with the review:
- `pytest_randomly` api: https://github.com/pytest-dev/pytest-randomly/blob/31f275de3a793e9890369eb5030cf7e8c620decb/src/pytest_randomly/__init__.py#L172

### CODE REVIEW

**Comment by sobolevn** [comment]
Looks like this test is flaky:

```
________________________ test_schema_create[Locale.SK] _________________________

schema = <mimesis.schema.Schema object at 0x7fa28394e4a0>

    def test_schema_create(schema):
        result = schema.create(5)
    
        assert len(result) == 5
        assert isinstance(result, list)
    
        first, *mid, last = result
    
        assert first["timestamp"] != last["timestamp"]
>       assert first["owner"]["creator"] != last["owner"]["creator"]
E       AssertionError: assert 'Milena Lukáčová' != 'Milena Lukáčová'

tests/test_schema.py:154: AssertionError
```

Seed for the repro: `--randomly-seed=26050`

**Comment by sobolevn** [comment]
Btw, I featured this tool in my new testing course: https://education.borshev.com/python-testing

Thanks a lot for maintaing it! Very useful :)

**Comment by lk-geimfari** [comment]
@sobolevn Thanks for this PR! Also thank you for once inspiring me to do Open Source — I'm here because of you. You are a real inspiration, Nikita!

**Comment by lk-geimfari** [comment]
@sobolevn Speaking about `unique` - let's make it better. I'll wait for your  issue.

**Comment by lk-geimfari** [comment]
@sobolevn Let me know if I can merge this PR.

**Comment by sobolevn** [comment]
I have to fix CI first, what I've done:
1. Coverage is now only uploaded with a single job
2. new `isort` configuration is applied
3. I don't know how to fix this flaky test just yet (I hope that it will just go away 😆)

**Comment by lk-geimfari** [comment]
I also noticed some unstable tests with some locales (for example `fa`), but I never get to them. I'm going to work on these tests quality.

**Comment by lk-geimfari** [comment]
@sobolevn Feel free to merge this PR when you'll finish. You have such permissions as I see.

**Comment by sobolevn** [comment]
I've moved `pypy` tests to a separate group, because they have troubles running C code like mypy or black.

**Comment by sobolevn** [comment]
Only `codecov` fails, but it has its own math:

Снимок экрана 2023-03-30 в 12 33 45


So, I don't really care :)

**Comment by lk-geimfari** [comment]
```
[{'defined_cls': {'t1': 'Dr.',
                  't2': 'Dr.',
                  't3': 'Ing.',
                  't4': 'Strč prst skrz krk.'},
  'id': '80a82a57-e34a-414f-ad48-e29496982e02',
  'name': 'žblnknúť',
  'owner': {'creator': 'Milena Lukáčová', 'email': 'raid1975@duck.com'},
  'timestamp': 1689143568,
  'zip_code': '408 01'},
 {'defined_cls': {'t1': 'Dr.',
                  't2': 'Dr.',
                  't3': 'Bc.',
                  't4': 'Strč prst skrz krk.'},
  'id': 'a310028b-c0f6-4289-b800-d0dd8d69a8d1',
  'name': 'žblnknúť',
  'owner': {'creator': 'Lucia Kováčová', 'email': 'passion2076@live.com'},
  'timestamp': 1316012516,
  'zip_code': '148 46'},
 {'defined_cls': {'t1': 'pani',
                  't2': 'pán',
                  't3': 'Dr.',
                  't4': 'Strč prst skrz krk.'},
  'id': '76695635-e25f-458f-ab5b-9cd52cba0bb9',
  'name': 'žblnknúť',
  'owner': {'creator': 'Romana Tóthová', 'email': 'makeup1959@duck.com'},
  'timestamp': 970845116,
  'zip_code': '409 74'},
 {'defined_cls': {'t1': 'Ing.',
                  't2': 'pán',
                  't3': 'Bc.',
                  't4': 'Strč prst skrz krk.'},
  'id': 'aff7475d-46bd-434f-9801-11c207ba1ae5',
  'name': 'žblnknúť',
  'owner': {'creator': 'Otília Vargová', 'email': 'creative1947@yahoo.com'},
  'timestamp': 1406496508,
  'zip_code': '858 21'},
 {'defined_cls': {'t1': 'Bc.',
                  't2': 'Bc.',
                  't3': 'Dr.',
                  't4': 'Strč prst skrz krk.'},
  'id': 'b31eef50-d40a-4322-a29f-f042ad98ae83',
  'name': 'žblnknúť',
  'owner': {'creator': 'Milena Lukáčová', 'email': 'ata1896@live.com'},
  'timestamp': 1041324390,
  'zip_code': '734 99'}]

````

It's funny, but seems that this happens because of small list of names and surnames for `SK`. Gonna fix this.

**Pull request merged**
