### PR TITLE
Better generation of Russian KPP 

### PR DESCRIPTION
**Pull request by treylav**
# I improved Russian KPP generation
Now the generation is more diverse due to the larger array of tax offices codes.

I also changed the registration reason code from random to real codes established by Russian law. **Since there are two kinds of codes, I added two arguments to let the user choose from them. I've set the parameters to their default values, so code that calls `kpp()` without parameters shouldn't break from these changes**. I hope my other changes didn't break compatibility too.

**~~Why didn't I write new tests?~~** 
KPP, due to its nature, is practically can't be validated without access to external data sources: for example, it does not have a check digit. In this context, I'm not sure how I can improve generation's testing.
upd: But I wrote test for warning message I added.

Neither my Python nor my English are close to fluent. I'll be glad to any of your suggestions. I see a lot of room for further improvement of the Russian locale in the project.

Thanks in advance.

## Checklist

- [x] I have read [contributing guidelines](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTING.rst)
- [x] I'm sure that I did not unrelated changes in this pull request
- [x] I have created at least one test case for the changes I have made
- [x] I have added myself to the [CONTRIBUTORS.rst](https://github.com/lk-geimfari/mimesis/blob/master/CONTRIBUTORS.rst)

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@treylav Please, fix style issues. Use `scripts/format.sh`

**Comment by treylav** [comment]
> @treylav Please, fix style issues. Use `scripts/format.sh`

Done in 1417c2c.

**Comment by treylav** [comment]
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions.

Hey,  @lk-geimfari, if there are no problems with my pull request, I will be glad if you merge it; if there is something to improve - I'm ready.

I don't mind continuing to slowly improve the generation of Russian IDs if you're interested.

**Comment by lk-geimfari** [comment]
@treylav Hi! There is nothing wrong in you PR. Sorry, I completely forgot about this PR. Can you please rebase and recreate it?

**Comment by treylav** [comment]
It looks like the synchronization went well without a rebase.

But if necessary, I'll recreate the branch.

**Comment by lk-geimfari** [comment]
Please, recreate PR.

**Pull request closed without merging**
