### PR TITLE
[WIP] Add greek locale

### PR DESCRIPTION
**Pull request by modkaffes**
This contains data for the greek locale. Will be updated as data is being added.

- [ ] Address
- [x] Business
- [x] Datetime
- [ ] Food
- [ ] Personal
- [ ] Science
- [ ] Text

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@modkaffes Great. I will track your activity in this PR.

**Comment by modkaffes** [comment]
@lk-geimfari, sure! I'd started work on this back in October, but somehow it fell behind. I'll try to complete it this time. Glad to see there's so many people involved!

**Comment by modkaffes** [comment]
Just so you know, I copied the `en` folder and I'm kind of converting this to locale specific data. If there's any points I need clarifications with, I'll ping you.

**Comment by lk-geimfari** [comment]
@modkaffes I add new languages in a similar way. Problems should not arise. But keep in mind that the English locale has data that is intended only for the United States.

**Comment by modkaffes** [comment]
Ok, after porting data from the us locale, I'll poke around other locale folders to see what other locale-specific data can be added.

**Comment by lk-geimfari** [comment]
@modkaffes Okay! Thank you for contributing! Support to the Greek locale is very important.

**Comment by lk-geimfari** [comment]
@modkaffes Just ping. I hope you're still interested in add of Greek locale.

**Comment by modkaffes** [comment]
@lk-geimfari Sure! I've been just terribly busy with work the past couple of weeks. I will resume as soon as time frees up.

**Comment by lk-geimfari** [comment]
@modkaffes Of course, I understand. It was be just ping. Thanks you.

**Comment by lk-geimfari** [comment]
@modkaffes Look at: #224

**Pull request closed without merging**
